name: Testing

on:
  push:
    branches: [ main ]
    paths:
      - '*.py'
      - '!client.py'
      - 'testing/*'

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.9"

      - name: Run automated testing
        run: python testing.py -multi_server
